# -*- coding: utf-8 -*-
"""mobile_app_ml_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JLsyHyBh9CLLMZNegWyrprIzKxASJHKQ

# Mobile App Success Predictor & Recommender
This notebook covers data preprocessing, visualization, machine learning, and recommendation system.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Load Dataset"""

df = pd.read_csv('/content/googleplaystore.csv')
print(f"DataFrame shape after loading: {df.shape}")
df.head()

"""## Data Cleaning"""

def convert_size(size):
    if size == 'Varies with device':
        return np.nan
    elif 'M' in str(size):
        return float(size.replace('M', ''))
    elif 'k' in str(size):
        return float(size.replace('k', '')) / 1024
    return np.nan

print(f"Initial DataFrame shape: {df.shape}")

df['Size'] = df['Size'].apply(convert_size)
df['Installs'] = df['Installs'].astype(str).str.replace('+', '', regex=False).str.replace(',', '', regex=False)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')
# Ensure 'Price' column is string type before using .str accessor
df['Price'] = df['Price'].astype(str).replace('Free', '0').str.replace('$', '', regex=False)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

print(f"Shape after initial conversions (before drop_duplicates): {df.shape}")
print(f"Number of nulls after conversions:\n{df.isnull().sum()}")

df.drop_duplicates(subset='App', inplace=True)
print(f"Shape after dropping duplicates: {df.shape}")
print(f"Number of nulls after dropping duplicates:\n{df.isnull().sum()}")

df.dropna(inplace=True)
print(f"Final DataFrame shape after dropna: {df.shape}")

df.head()

"""## Encoding"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])
df['Content Rating'] = le.fit_transform(df['Content Rating'])

"""## Visualization"""

plt.figure()
sns.scatterplot(x=df['Reviews'], y=df['Rating'])
plt.title('Reviews vs Ratings')
plt.show()

X = df[['Category', 'Size', 'Installs', 'Price', 'Content Rating']]

# Convert categorical columns
X = pd.get_dummies(X, columns=['Category', 'Content Rating'], drop_first=True)

"""## Model Training"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

y = df['Rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)

preds = model.predict(X_test)

print('MAE:', mean_absolute_error(y_test, preds))
print('RMSE:', np.sqrt(mean_squared_error(y_test, preds)))

"""## Recommendation System"""

from sklearn.metrics.pairwise import cosine_similarity

features = df[['Category', 'Price', 'Content Rating']]
similarity = cosine_similarity(features)

def recommend_apps(app_name):
    idx = df[df['App'] == app_name].index[0]
    scores = list(enumerate(similarity[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    app_indices = [i[0] for i in scores]
    return df.iloc[app_indices][['App', 'Rating']]

# Example
# recommend_apps('Instagram')